### ISSUE TITLE
Move biojs.net2 to biojs.net 

### ISSUE THREAD

**Issue by daviddao** [biojs/biojs.net2#1]
Great page @jessica-jordan ! I love the new redesign - Also the fact that we moved back to our old logo! In order to keep our numbers of repositories clean and structured, it would be nice to move biojs.net2 to biojs.net and deprecate the old biojs page. In that way we can also keep our stars for the homepage. Do you want to do a PR?

**Comment by jayjayjpg** [comment]
That's a good point. I will check what has to be edited on heroku to make the move

**Comment by jayjayjpg** [comment]
Page resources for our automatic heroku build are now available under https://github.com/biojs/biojs.net preserving our former git history.
