### ISSUE TITLE
Password for Ghost

### ISSUE THREAD

**Issue by daviddao** [biojs/biojs.net2#2]
@jessica-jordan Is there a password for BioJS Ghost? If yes, can anyone from the organisation edit the website?

**Comment by jayjayjpg** [comment]
Yes, the theme (biojs-theme) can be edited via cloning the repo and setting up the ghost blog locally. You can then make your changes and create a PR which will be uploaded to the live site once merged. 

If you just want to edit the web content (e.g. create a new post) I can invite you or anyone else who would like to add / edit content to the CMS. You will then receive an invitation e-mail to access the Ghost backend via the url https://biojsnet.herokuapp.com/ghost

**Comment by daviddao** [comment]
Sure :) - I am looking forward to the invite!

**Comment by wilzbach** [comment]
+1 please :)

**Comment by wilzbach** [comment]
(ping)

**Comment by jayjayjpg** [comment]
@daviddao @greenify I just sent out the invitation to your github associated email addresses. Please let me know if you can't find any e-mail in your inbox (or spam folder) :tiger:

**Comment by wilzbach** [comment]
Got it - thanks :)

**Comment by daviddao** [comment]
thanks!
