### ISSUE TITLE
Map url http(s)://biojs.net to new herokuapp based website on https://biojsnet.herokuapp.com 

### ISSUE THREAD

**Issue by jayjayjpg** [biojs/biojs.net2#3]
Currently the DNS settings for http(s)://biojs.net direct to the new website on heroku, but the url will automatically change in the browser window once the page has loaded. What do we have to change in the DNS settings to create persistent urls like
https://biojs.net or https://biojs.net/gsoc when the herokuapp based website is browsed?

**Comment by wilzbach** [comment]
Just Change the dns to point to Heroku 
Best, 

## Seb 
- Sent from mobile. Please excuse any typos 
- Don't give spying a chance - use encryption
- Please use my PGP key @pgp.wilzba.ch/seb.asc

**Comment by jayjayjpg** [comment]
Hi @greenify I did make changes to the DNS, as this is why the url http://biojs.net will redirect to https://biojsnet.herokuapp.com currently. But the url doesn't persist in the browser bar. Not sure what to change in the DNS settings here specifically

**Comment by wilzbach** [comment]
Did you enable the domain at Heroku?

**Comment by jayjayjpg** [comment]
@greenify Yes I did using the heroku toolbelt according to this guide:

https://devcenter.heroku.com/articles/custom-domains

I just added the domain using `heroku domains:add` and pointed the DNS to the target specified there

**Comment by wilzbach** [comment]
Hmm I am still at my phone, but maybe somewhere within ghost there is still a default domain?

**Comment by wilzbach** [comment]
It's definitely done by Ghost, but might be still in the Cloudfare cache.

```
curl -v biojs.net
* Rebuilt URL to: biojs.net/
*   Trying 104.28.21.90...
* Connected to biojs.net (104.28.21.90) port 80 (#0)
> GET / HTTP/1.1
> Host: biojs.net
> User-Agent: curl/7.47.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 09 Mar 2016 11:47:59 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 65
< Connection: keep-alive
< Set-Cookie: __cfduid=da10213720e2d67f27641ffc86d97bb191457524079; expires=Thu, 09-Mar-17 11:47:59 GMT; path=/; domain=.biojs.net; HttpOnly
< X-Powered-By: Express
< Location: https://biojsnet.herokuapp.com/
< Vary: Accept, Accept-Encoding
< Via: 1.1 vegur
< Server: cloudflare-nginx
< CF-RAY: 280e4b99ffed370e-ARN
< 
* Connection #0 to host biojs.net left intact
Moved Permanently. Redirecting to https://biojsnet.herokuapp.com/
```

**Comment by daviddao** [comment]
@jessica-jordan @greenify any news regarding this issue?

**Comment by wilzbach** [comment]
Bump! Unfortunately there is not much that I can do.
@jessica-jordan did you try to do clear the Cloudfare's cache?

Moreover I recommend to do a curl on the heroku machine, if it redirects to heroku, it's an issue with Ghost. Otherwise Cloudfare or Heroku.

**Comment by jayjayjpg** [comment]
@greenify I haven't managed to get into that up until now, but I should
have some time to do that in the next couple of days. Hopefully this will
already fix it.

**Comment by jayjayjpg** [comment]
It seems I found the issue. As our herokuapp relies on the https protocol due to Ghost CMS we would have to setup an SSL endpoint to point the custom domain at cloudfare to. Unfortunately, the SSL addon is a paid service, so I will have to check with Manny first how to proceed from here:

[Setting up custom domain on cloudfare for heroku](https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku)
[How-to - SSL endpoint setup on heroku](https://devcenter.heroku.com/articles/ssl-endpoint)

**Comment by wilzbach** [comment]
You can also change the name server back and avoid using cloudfare - then it's for free.

**Comment by jayjayjpg** [comment]
@greenify Can you explain what things have to be done to make the free url setup work? I'm not so familiar with DNS settings and hosting, yet, so any detailed instruction is more than welcome!

**Comment by wilzbach** [comment]
I don't know where you pay for the biojs domain, but there you can change the dns back. Maybe @Denisschwarz can help?

**Comment by jayjayjpg** [comment]
@wilzbach I just updated the heroku build when adding the ruby buildpack for issue #12 and mapping from https://biojs.net -> biojsnet.herokuapp.com now works!

**Comment by wilzbach** [comment]
:)
